version: '1.0'

services:

  # The Application (Laravel App)
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  # The Web Server (e.g., Nginx or Apache)
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database (MySQL)
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=fullstack_ecommerce"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=qwerty123"
      - "MYSQL_ROOT_PASSWORD=qwerty123"
    ports:
        - "33061:3306"

  # Redis Service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
